// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.41537 Microsoft Reciprocal License (Ms-RL) 
//    <NameSpace>InformediaCORE.Common.Xml</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace InformediaCORE.Common.Xml
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class XmlCollection
    {

        private string accessionField;

        private string descriptionShortField;

        private string biographyShortField;

        private string firstNameField;

        private string lastNameField;

        private string preferredNameField;

        private string websiteURLField;

        private string regionField;

        private string birthCityField;

        private string birthStateField;

        private string birthCountryField;

        private XmlGenderType genderField;

        private System.Nullable<System.DateTime> birthDateField;

        private System.Nullable<System.DateTime> deceasedDateField;

        private string portraitPathField;

        private List<XmlSession> sessionsField;

        private List<XmlAnnotation> annotationsField;

        private List<string> partitionsField;

        public XmlCollection()
        {
            this.partitionsField = new List<string>();
            this.annotationsField = new List<XmlAnnotation>();
            this.sessionsField = new List<XmlSession>();
            this.biographyShortField = "";
        }

        public string Accession
        {
            get
            {
                return this.accessionField;
            }
            set
            {
                this.accessionField = value;
            }
        }

        public string DescriptionShort
        {
            get
            {
                return this.descriptionShortField;
            }
            set
            {
                this.descriptionShortField = value;
            }
        }

        public string BiographyShort
        {
            get
            {
                return this.biographyShortField;
            }
            set
            {
                this.biographyShortField = value;
            }
        }

        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }

        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }

        public string PreferredName
        {
            get
            {
                return this.preferredNameField;
            }
            set
            {
                this.preferredNameField = value;
            }
        }

        public string WebsiteURL
        {
            get
            {
                return this.websiteURLField;
            }
            set
            {
                this.websiteURLField = value;
            }
        }

        public string Region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }

        public string BirthCity
        {
            get
            {
                return this.birthCityField;
            }
            set
            {
                this.birthCityField = value;
            }
        }

        public string BirthState
        {
            get
            {
                return this.birthStateField;
            }
            set
            {
                this.birthStateField = value;
            }
        }

        public string BirthCountry
        {
            get
            {
                return this.birthCountryField;
            }
            set
            {
                this.birthCountryField = value;
            }
        }

        public XmlGenderType Gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }

        public System.Nullable<System.DateTime> BirthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }

        public System.Nullable<System.DateTime> DeceasedDate
        {
            get
            {
                return this.deceasedDateField;
            }
            set
            {
                this.deceasedDateField = value;
            }
        }

        public string PortraitPath
        {
            get
            {
                return this.portraitPathField;
            }
            set
            {
                this.portraitPathField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("Session", IsNullable = false)]
        public List<XmlSession> Sessions
        {
            get
            {
                return this.sessionsField;
            }
            set
            {
                this.sessionsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("Annotation", IsNullable = false)]
        public List<XmlAnnotation> Annotations
        {
            get
            {
                return this.annotationsField;
            }
            set
            {
                this.annotationsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("Partition", IsNullable = false)]
        public List<string> Partitions
        {
            get
            {
                return this.partitionsField;
            }
            set
            {
                this.partitionsField = value;
            }
        }
    }

    public enum XmlGenderType
    {

        /// <remarks/>
        Female,

        /// <remarks/>
        Male,
    }

    public partial class XmlSession
    {

        private int sessionOrderField;

        private string interviewerField;

        private System.DateTime interviewDateField;

        private string locationField;

        private string videographerField;

        private string sponsorField;

        private string sponsorURLField;

        private string sponsorImagePathField;

        public int SessionOrder
        {
            get
            {
                return this.sessionOrderField;
            }
            set
            {
                this.sessionOrderField = value;
            }
        }

        public string Interviewer
        {
            get
            {
                return this.interviewerField;
            }
            set
            {
                this.interviewerField = value;
            }
        }

        public System.DateTime InterviewDate
        {
            get
            {
                return this.interviewDateField;
            }
            set
            {
                this.interviewDateField = value;
            }
        }

        public string Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        public string Videographer
        {
            get
            {
                return this.videographerField;
            }
            set
            {
                this.videographerField = value;
            }
        }

        public string Sponsor
        {
            get
            {
                return this.sponsorField;
            }
            set
            {
                this.sponsorField = value;
            }
        }

        public string SponsorURL
        {
            get
            {
                return this.sponsorURLField;
            }
            set
            {
                this.sponsorURLField = value;
            }
        }

        public string SponsorImagePath
        {
            get
            {
                return this.sponsorImagePathField;
            }
            set
            {
                this.sponsorImagePathField = value;
            }
        }
    }
}
