// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.41537 Microsoft Reciprocal License (Ms-RL) 
//    <NameSpace>InformediaCORE.Common.Xml</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace InformediaCORE.Common.Xml
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class XmlMovie
    {

        private string nameField;

        private string pathField;

        private string collectionField;

        private string abstractField;

        private int tapeNumberField;

        private int sessionNumberField;

        private List<XmlAnnotation> annotationsField;

        private List<XmlSegment> segmentsField;

        public XmlMovie()
        {
            this.segmentsField = new List<XmlSegment>();
            this.annotationsField = new List<XmlAnnotation>();
        }

        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public string Path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }

        public string Collection
        {
            get
            {
                return this.collectionField;
            }
            set
            {
                this.collectionField = value;
            }
        }

        public string Abstract
        {
            get
            {
                return this.abstractField;
            }
            set
            {
                this.abstractField = value;
            }
        }

        public int TapeNumber
        {
            get
            {
                return this.tapeNumberField;
            }
            set
            {
                this.tapeNumberField = value;
            }
        }

        public int SessionNumber
        {
            get
            {
                return this.sessionNumberField;
            }
            set
            {
                this.sessionNumberField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("Annotation", IsNullable = false)]
        public List<XmlAnnotation> Annotations
        {
            get
            {
                return this.annotationsField;
            }
            set
            {
                this.annotationsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("Segment", IsNullable = false)]
        public List<XmlSegment> Segments
        {
            get
            {
                return this.segmentsField;
            }
            set
            {
                this.segmentsField = value;
            }
        }
    }

    public partial class XmlSegment
    {

        private string titleField;

        private string abstractField;

        private XmlTimeFormatSpecifier timeFormatField;

        private System.DateTime startTimeField;

        private System.DateTime endTimeField;

        private List<string> transcriptField;

        private List<XmlAnnotation> annotationsField;

        public XmlSegment()
        {
            this.annotationsField = new List<XmlAnnotation>();
            this.transcriptField = new List<string>();
        }

        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        public string Abstract
        {
            get
            {
                return this.abstractField;
            }
            set
            {
                this.abstractField = value;
            }
        }

        public XmlTimeFormatSpecifier TimeFormat
        {
            get
            {
                return this.timeFormatField;
            }
            set
            {
                this.timeFormatField = value;
            }
        }

        public System.DateTime StartTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
            }
        }

        public System.DateTime EndTime
        {
            get
            {
                return this.endTimeField;
            }
            set
            {
                this.endTimeField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("Paragraph")]
        public List<string> Transcript
        {
            get
            {
                return this.transcriptField;
            }
            set
            {
                this.transcriptField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("Annotation", IsNullable = false)]
        public List<XmlAnnotation> Annotations
        {
            get
            {
                return this.annotationsField;
            }
            set
            {
                this.annotationsField = value;
            }
        }
    }

    /// <summary>
    /// Enumeration defining the valid time range formats.
    /// </summary>
    public enum XmlTimeFormatSpecifier
    {

        /// <summary>
        /// Time span starting at HH:MM:SS through HH:MM:SS
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("HMS-HMS")]
        HMSHMS,

        /// <summary>
        /// Time span starting at HH:MM:SS through END of video file.
        /// </summary>
        [System.Xml.Serialization.XmlEnumAttribute("HMS-END")]
        HMSEND,
    }
}
